[package]
name = "managarr"
version = "0.1.0"
authors = ["Alex Clarke <alex.j.tusa@gmail.com>"]
description = "A TUI for managing *arr servers"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0.30", features = ["help", "usage", "error-context", "derive"] }
confy = { version = "0.5.1", default_features = false, features = ["yaml_conf"] }
crossterm = "0.25.0"
derivative = "2.2.0"
indoc = "1.0.8"
log = "0.4.17"
log4rs = { version = "1.2.0", features = ["file_appender"] }
regex = "1.7.1"
reqwest = { version = "0.11.13", features = ["json"] }
serde_yaml = "0.9.16"
serde_json = "1.0.91"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.24.1", features = ["full"] }
tui = "0.19.0"
urlencoding = "2.1.2"
