[package]
name = "managarr"
version = "0.0.34"
authors = ["Alex Clarke <alex.j.tusa@gmail.com>"]
description = "A TUI to manage your Servarrs"
keywords = ["managarr", "tui-rs", "dashboard", "servarr", "tui"]
documentation = "https://github.com/Dark-Alex-17/managarr"
repository = "https://github.com/Dark-Alex-17/managarr"
homepage = "https://github.com/Dark-Alex-17/managarr"
readme = "README.md"
edition = "2021"
rust-version = "1.75.0"

[dependencies]
anyhow = "1.0.68"
backtrace = "0.3.67"
bimap = "0.6.3"
chrono = { version = "0.4", features = ["serde"] }
confy = { version = "0.6.0", default_features = false, features = ["yaml_conf"] }
crossterm = "0.27.0"
derivative = "2.2.0"
human-panic = "1.1.3"
indoc = "2.0.0"
log = "0.4.17"
log4rs = { version = "1.2.0", features = ["file_appender"] }
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["json"] }
serde_yaml = "0.9.16"
serde_json = "1.0.91"
serde = { version = "1.0", features = ["derive"] }
strum = {version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = "0.7.8"
ratatui = { version = "0.26.0", features = ["all-widgets"] }
urlencoding = "2.1.2"

[dev-dependencies]
mockito = "1.0.0"
pretty_assertions = "1.3.0"
rstest = "0.18.2"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["prepush-hook", "precommit-hook", "run-cargo-test", "run-cargo-clippy"]

[[bin]]
bench = false
path = "src/main.rs"
name = "managarr"

[profile.release]
lto = true
codegen-units = 1
