#!/bin/sh

set -e

echo "Running pre-push hook:"

echo "Executing: cargo fmt --check"
cargo fmt --check

echo "Executing: cargo clippy --all"
cargo clippy --all

echo "Executing: cargo test --all"
cargo test --all
