name: Bug Report
description: Create a report to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: Thank you for filing a bug report!
  - type: textarea
    id: problem
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicate the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      value: |
        <!-- Ideally provide a key sequence and/or asciinema.org recording. --> 

        I tried this:

        1. `managarr`

        I expected this to happen:

        Instead, this happened:
  - type: textarea
    id: managarr-log
    attributes:
      label: Managarr log
      description: Include the Managarr log file to help diagnose the issue.
      value: |
        | OS      | Log file location                                     |
        | ------- | ----------------------------------------------------- |
        | Linux   | `~/.cache/managarr/managarr.log`                      |
        | Mac     | `~/Library/Logs/managarr/managarr.log`                |
        | Windows | `C:\Users\<User>\AppData\Local\managarr\managarr.log` |

        ```
        please provide a copy of your managarr log file here if possible, you may need to redact some of the lines
        ```

  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: Linux / macOS / Windows
    validations:
      required: true
  - type: input
    id: terminal-emulator
    attributes:
      label: Terminal Emulator
      placeholder: wezterm 20220101-133340-7edc5b5a
    validations:
      required: true
  - type: input
    id: managarr-version
    attributes:
      label: Managarr Version
      description: >
        Managarr version (`managarr --version` if using a release, `git describe` if building
        from main).
        **Make sure that you are using the [latest managarr release](https://github.com/Dark-Alex-17/managarr/releases) or a newer main build**
      placeholder: "managarr 0.0.36"
    validations:
      required: true
